In [79]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Mineração de Regras de Associação com python, Apriori e SQL/03. Base vestibular/vestibular_mySQL.csv')
df.head()

,pontos,curso,grau,periodo,sexo,idade,local_origem,tipo_instituicao,renda_familiar,tipo_residencia,grau_escolaridade,motivo,transporte,instrucao_pai,instrucao_mae,automovel,livros,leitura,internet
0,20-40 pontos,ENGENHARIA AGRONÔMICA,SUPERIOR,INTEGRAL,M,entre 23 e 30,Zona Urbana,Apenas em escola pública,"Maior que R$ 1530,00",Alugada,Médio Completo,Realização pessoal,próprio,Ensino Médio Incompleto,Ensino Médio Completo,Sim,Nenhum livro,Outro,Diariamente
1,40-60 pontos,ENSINO MÉDIO E TÉCNICO EM AGROPECUÁRIA INTEGRADO,ENSINO MÉDIO E TÉCNICO,INTEGRAL,M,menor 17,Zona Rural,Apenas em escola pública,"R$ 511,00 a 765,00",Própria,Fundamental,Realização pessoal,ônibus/van,Ensino Fundam. incompleto,Ensino Fundam. incompleto,Sim,1 ou 2 livros,Outro,Não utiliza
2,60-80 pontos,INFORMÁTICA,TÉCNICO,NOTURNO,F,entre 23 e 30,Zona Urbana,Apenas em escola pública,"R$ 511,00 a 765,00",Própria,Médio Completo,Possibilidades no mercado de trabalho,carona,Ensino Fundam. incompleto,Ensino Fundamental Completo,Não,1 ou 2 livros,Outro,Diariamente
3,40-60 pontos,AGROPECUÁRIA,TÉCNICO,INTEGRAL,M,entre 18 e 22,Zona Urbana,Apenas em escola pública,"R$ 1276,00 a 1530,00",Própria,Médio Completo,outro motivo,ônibus/van,Ensino Médio Completo,Ensino Médio Incompleto,Sim,1 ou 2 livros,Ficção,Diariamente
4,40-60 pontos,CIÊNCIA DA COMPUTAÇÃO,SUPERIOR,NOTURNO,F,entre 18 e 22,Zona Urbana,Apenas em escola pública,"R$ 511,00 a 765,00",Própria,Médio Incompleto,Possibilidades no mercado de trabalho,ônibus/van,Ensino Fundam. incompleto,Ensino Médio Completo,Sim,Mais de 5 livros,Outro,Diariamente

In [3]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5956 sha256=3f42473eb1452d790a05659f3330fca1941441dff2b0c0a83be048a2c1001956
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [64]:
from apyori import apriori

In [45]:
len(df)

1326

In [80]:
# Colocando os dados na segunda forma da parte teorica, exigido pelo apyyorri
transacoes = []
for i in range(len(df)):
  #print(base_mercado.values[i]) # Vai mostrar as linhas
  transacoes.append([str(df.values[i, j]) for j in range(17)]) # Pegando todos os valores da linha i

In [81]:
print(transacoes[3])

['40-60 pontos', 'AGROPECUÁRIA', 'TÉCNICO', 'INTEGRAL', 'M', 'entre 18 e 22', 'Zona Urbana', 'Apenas em escola pública', 'R$ 1276,00 a 1530,00', 'Própria', 'Médio Completo', 'outro motivo', 'ônibus/van', 'Ensino Médio Completo', 'Ensino Médio Incompleto', 'Sim', '1 ou 2 livros']

In [82]:
# Vai criar as regras
regras = apriori(transacoes, min_support=0.2, min_confidence=0.7, min_lift=1.15, min_lenght=2)
regras = list(regras)
len(regras)

94

In [83]:
# Armazenando os valores para ficar mais legivel
valores_x = [] # Valor do SE
valores_y = [] # Valor do ENTAO
suporte = []
confianca = []
lift = []
# Resultados tem as regras de cada conjunto
for resultado in regras:
  sup = resultado[1] # Suporte
  result_rule = resultado[2] # Regras do conjunto em questao

  # precisamos percorrer as regras
  for regra in result_rule:
    x = list(regra[0]) # Pega o x
    y = list(regra[1]) # pega o y
    c = regra[2] # COnfiança
    l = regra[3] # lift

    # Colocando nas listas
    valores_x.append(x)
    valores_y.append(y)
    suporte.append(sup)
    confianca.append(c)
    lift.append(l)

In [84]:
regras_df = pd.DataFrame({'SE': valores_x,
                          'ENTAO': valores_y,
                          'Suporte': suporte,
                          'Confianca': confianca,
                          'Lift': lift})

regras_df.sort_values(by='Confianca', ascending=False)

,SE,ENTAO,Suporte,Confianca,Lift
324,"[Fundamental, INTEGRAL, Zona Urbana, menor 17]",[ENSINO MÉDIO E TÉCNICO],0.202112,1.000000,3.013636
322,"[Fundamental, menor 17, Zona Urbana, ENSINO MÉ...",[INTEGRAL],0.202112,1.000000,1.927326
228,"[Fundamental, menor 17, ENSINO MÉDIO E TÉCNICO]",[INTEGRAL],0.244344,1.000000,1.927326
217,"[Fundamental, INTEGRAL, Zona Urbana]",[ENSINO MÉDIO E TÉCNICO],0.239819,1.000000,3.013636
215,"[Fundamental, Zona Urbana, ENSINO MÉDIO E TÉCN...",[INTEGRAL],0.239819,1.000000,1.927326
...,...,...,...,...,...
170,[Fundamental],"[menor 17, INTEGRAL, Apenas em escola pública]",0.208899,0.706633,3.165523
129,[Fundamental],"[menor 17, ENSINO MÉDIO E TÉCNICO, Apenas em e...",0.208899,0.706633,3.165523
278,[Fundamental],"[menor 17, INTEGRAL, ENSINO MÉDIO E TÉCNICO, A...",0.208899,0.706633,3.165523
273,"[NOTURNO, Própria]","[Médio Completo, Zona Urbana]",0.222474,0.702381,1.547105
191,"[NOTURNO, Zona Urbana]","[ônibus/van, Apenas em escola pública]",0.266214,0.701789,1.151699

No geral, para melhorar a qualidade das regras com apriori, temos duas opções:


```
1. Testar apagar alguns atributos e ver como o algoritmo se comporta, analisando se as regras se tornaram mais relevantes ou nao
2. alterar os parametros e fazer a mesma analise
```

Nesse caso, está aparecendo muito Ensino medio e integral, se quisermos olhar regras que nao o envolvam, podemos deletar eesse atributo